steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:latest', './exercise-1']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-app:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'cluster-candidato2' 
    - '--zone'
    - 'us-east1-b' 
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'kubectl'
    - 'set'
    - 'image'
    - 'deployment/flask-app'
    - 'flask-app=gcr.io/$PROJECT_ID/flask-app:latest'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'kubectl'
    - 'rollout'
    - 'status'
    - 'deployment/flask-app'

images:
  - 'gcr.io/$PROJECT_ID/flask-app:latest'
